version: '2.0'
services:
  mysql:
    restart: always
    image: mysql:5.7
    command: ['mysqld','--character-set-server=utf8']
    command: --default-authentication-plugin=mysql_native_password
    command: --disable-partition-engine-check
    command: --explicit_defaults_for_timestamp
    command: mysqld --innodb-buffer-pool-size=20M
    ports:
     - 3306:3306
    environment:
     - "MYSQL_DATABASE=mirth-test"
     - "MYSQL_USER=mirth"
     - "MYSQL_PASSWORD=password"
     - "MYSQL_ROOT_PASSWORD=password"
    volumes:
     - databasevolume:/var/lib/mysql
  openemr:
    restart: always
    image: openemr/openemr
    ports:
     - 880:80
    volumes:
    - assetsvolume01:/var/www/localhost/htdocs/openemr/public:rw
    - configvolume01:/var/www/localhost/htdocs/openemr/sites/default:rw
    - configvolume02:/var/www/localhost/htdocs/openemr/interface/modules/zend_modules/config:rw
    - logvolume01:/var/log
    - nodemodules:/var/www/localhost/htdocs/openemr/node_modules:rw
    - vendordir:/var/www/localhost/htdocs/openemr/vendor:rw
    - ccdamodule:/var/www/localhost/htdocs/openemr/ccdaservice:rw
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASS: password
      MYSQL_USER: root
      MYSQL_PASS: password
      OE_USER: admin
      OE_PASS: pass
    depends_on:
    - mysql

  mirth-connect:
    build: mirth-connect
    image: fabrom/mirth-connect
    container_name: mc-mirthconnect
    volumes:
      - "./mirth-connect/mirth.properties:/opt/mirth-connect/conf/mirth.properties:rw"
      - "./data/spools/:/var/spool/mirth/:rw"
    ports: 
      - "8000:8080"
      - "8443:8443"
    depends_on:
      - mysql

  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    ports:
     - 81:80
    environment:
      PMA_HOST: mysql
    depends_on:
     - mysql
volumes:
  databasevolume: {}
  assetsvolume01: {}
  configvolume01: {}
  configvolume02: {}
  logvolume01: {}
  nodemodules: {}
  vendordir: {}
  ccdamodule: {}
